seleniumhub:
  image: selenium/hub:3.8.1
  ports:
  - 4444:4444

firefoxnode:
  image: selenium/node-firefox:3.8.1
  environment:
    SCREEN_WIDTH: 2880
    SCREEN_HEIGHT: 1800
  ports:
  - 5900
  links:
  - seleniumhub:hub


chromenode:
  image: selenium/node-chrome:3.8.1
  environment:
    SCREEN_WIDTH: 2880
    SCREEN_HEIGHT: 1800
  ports:
  - 5900
  links:
  - seleniumhub:hub